USE [master]
GO

IF DB_ID('FARMACIA_PROGRA4') IS NOT NULL
BEGIN
  DROP DATABASE [FARMACIA_PROGRA4]
END
GO

CREATE DATABASE [FARMACIA_PROGRA4]
GO
USE [FARMACIA_PROGRA4]
GO

CREATE SCHEMA [SCH_FARMACIA_PROGRA4]
GO
CREATE TABLE [SCH_FARMACIA_PROGRA4].[USUARIOS] ( --esta no
    [Id_USUARIO] INT IDENTITY(1,1),
    [IDENTIFICACION_USUARIO] NVARCHAR(20) NOT NULL,
    [NOMBRE_COMPLETO_USUARIO] NVARCHAR(100) NOT NULL,
    [CORREO_USUARIO] NVARCHAR(100) NOT NULL,
    [Tipo_Usuario] NVARCHAR(20)  NOT NULL, -- diferente
    [Estado_USUARIO] NVARCHAR(10) NOT NULL,
    [Contrasena_USUARIO] NVARCHAR(255) NOT NULL


		CONSTRAINT [PK_USUARIOS] PRIMARY KEY CLUSTERED
	(
		[Id_USUARIO] ASC
	)
)
GO

---Se realiza un  CRUD EN C#

CREATE TABLE [SCH_FARMACIA_PROGRA4].[Clientes] (
    [ID_CLIENTES] INT IDENTITY(1,1),
    [Identificacion] NVARCHAR(20) NOT NULL,
    [Nombre_Cliente] NVARCHAR(100)NOT NULL,
    [Correo] NVARCHAR(100) 

		CONSTRAINT [PK_Clientes] PRIMARY KEY CLUSTERED
	(
		[ID_CLIENTES] ASC
	)
)
GO

--Se puede eliminar las tablas que no tenga facturas o productos asociados

CREATE TABLE [SCH_FARMACIA_PROGRA4].[TiposProductos] (
    [Codigo_TIPO_Producto] NVARCHAR(20),
    [Descripcion_TIPO_Producto] NVARCHAR(255) NOT NULL

		CONSTRAINT [PK_TiposProductos] PRIMARY KEY CLUSTERED
	(
		[Codigo_TIPO_Producto] ASC
	)
)
GO

-- se crealiza un CRUD - de los tipos de productos

--Se realiza un CRUD en c#

-- Crear la tabla de productos
CREATE TABLE [SCH_FARMACIA_PROGRA4].[Productos] ( 
    [Codigo_PRODUCTO] NVARCHAR(20) NOT NULL,
    [Descripcion_PRODUCTO] NVARCHAR(255) NOT NULL,
    [Precio] DECIMAL(10, 2) NOT NULL,
    [Estado] NVARCHAR(20) NOT NULL,
    [CantidadStock] INT NOT NULL,
	[Codigo_TIPO_Producto] NVARCHAR(20)

    CONSTRAINT [PK_Productos] PRIMARY KEY CLUSTERED
	(
		[Codigo_PRODUCTO] ASC
	)
)
GO


-- Se realiza CRUD 


CREATE TABLE [SCH_FARMACIA_PROGRA4].[Facturas] (
    [Codigo_FACTURA] NVARCHAR(20), -- AUTO GENERADO
    [FechaCompra] DATETIME NOT NULL, --FECHA TIENE QUE OBLIGATORIA
	[Cantidad] INT NOT NULL,
    [MetodoPago] NVARCHAR(20) NOT NULL, -- EN EL CASO QUE NO EXISTE DEBE DE HABER UN BOTON DE INGRESAR -- EFECTIVO - SINPE - TARJETA
	[ID_CLIENTES] INT NOT NULL,

	 CONSTRAINT [PK_Facturas] PRIMARY KEY CLUSTERED
	(
		[Codigo_FACTURA] ASC
	)
)
GO


CREATE TABLE [SCH_FARMACIA_PROGRA4].[DetallesFactura] (
     [Id_DETALLES_FACTURA] INT IDENTITY(1,1), -- NO ME LO MUESTRA EN LA PANTALLA
     [Subtotal] DECIMAL(10, 2) NOT NULL, -- ESTE 
     [Total] DECIMAL(10, 2) NOT NULL, -- ESTE OTRA TABLA
	 [Codigo_FACTURA] NVARCHAR(20) NOT NULL,
	 [Codigo_PRODUCTO] NVARCHAR(20) NOT NULL,

  CONSTRAINT [PK_DetallesFactura] PRIMARY KEY CLUSTERED
	(
		[Id_DETALLES_FACTURA] ASC
	)
)
GO


-- No se debe tener el controlador editar ni la vista 
-- Se realiza un crud y un viewbag que muestra que si esta seguro en ingresar la factura


--listo necio--
--fk productos
ALTER TABLE [SCH_FARMACIA_PROGRA4].[Productos]
ADD CONSTRAINT [FK_PRODUCTOS_TIPO_PRODUCTO_CODIGO] FOREIGN KEY ([Codigo_TIPO_Producto])
REFERENCES [SCH_FARMACIA_PROGRA4].[TiposProductos]([Codigo_TIPO_Producto])
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[Productos]
CHECK CONSTRAINT [FK_PRODUCTOS_TIPO_PRODUCTO_CODIGO]
GO

--fks facturas
ALTER TABLE [SCH_FARMACIA_PROGRA4].[Facturas]
ADD CONSTRAINT [FK_FACTURAS_CLIENTES_ID] FOREIGN KEY ([ID_CLIENTES])
REFERENCES [SCH_FARMACIA_PROGRA4].[Clientes]([ID_CLIENTES])
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[Facturas]
CHECK CONSTRAINT [FK_FACTURAS_CLIENTES_ID]
GO

--FKS DETALLES FACTURA
--fks detalles factura
ALTER TABLE [SCH_FARMACIA_PROGRA4].[DetallesFactura]
ADD CONSTRAINT [FK_DETALLES_FACTURAS_CODIGO] FOREIGN KEY ([Codigo_FACTURA])
REFERENCES [SCH_FARMACIA_PROGRA4].[Facturas]([Codigo_FACTURA])
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[DetallesFactura]
CHECK CONSTRAINT [FK_DETALLES_FACTURAS_CODIGO]
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[DetallesFactura]
ADD CONSTRAINT [FK_DETALLES_PRODUCTOS_CODIGO] FOREIGN KEY ([Codigo_PRODUCTO])
REFERENCES [SCH_FARMACIA_PROGRA4].[Productos]([Codigo_PRODUCTO])
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[DetallesFactura]
CHECK CONSTRAINT [FK_DETALLES_PRODUCTOS_CODIGO]
GO