USE [master]
GO

IF DB_ID('FARMACIA_PROGRA4') IS NOT NULL
BEGIN
  DROP DATABASE [FARMACIA_PROGRA4]
END
GO

CREATE DATABASE [FARMACIA_PROGRA4]
GO
USE [FARMACIA_PROGRA4]
GO

CREATE SCHEMA [SCH_FARMACIA_PROGRA4]
GO

CREATE TABLE [SCH_FARMACIA_PROGRA4].[T_ROLES]
(
	[ID_ROLE] INT NOT NULL,
	[NOMBRE] VARCHAR(50) NOT NULL


	CONSTRAINT [PK_T_ROLES] PRIMARY KEY CLUSTERED
	(
		[ID_ROLE] ASC
	)
)
GO

CREATE TABLE [SCH_FARMACIA_PROGRA4].[T_USUARIOS]
(
	[ID_USUARIO] INT NOT NULL,
	[IDENTIFICACION] VARCHAR(50) UNIQUE NOT NULL,
	[NOMBRE] VARCHAR(100) NOT NULL,
	[APELLIDO] VARCHAR(100) NOT NULL,
	[CORREO] VARCHAR(50) NOT NULL,
	[CLAVE] VARCHAR(50) NOT NULL,
	[ID_ROLE] INT NOT NULL,


	CONSTRAINT [PK_T_USUARIOS] PRIMARY KEY CLUSTERED
	(
		[ID_USUARIO] ASC
	)
)
GO

CREATE TABLE [SCH_FARMACIA_PROGRA4].[T_TIPO_DE_PRODUCTOS]
(
	[ID_TIPO_PRODUCTO] INT NOT NULL,
	[NOMBRE_TIPO_PRODUCTO] VARCHAR(100) NOT NULL,
	[DESCRIPCION] VARCHAR(100) NOT NULL,


	CONSTRAINT [PK_T_TIPO_DE_PRODUCTOS] PRIMARY KEY CLUSTERED
	(
		[ID_TIPO_PRODUCTO] ASC
	)
)
GO

CREATE TABLE [SCH_FARMACIA_PROGRA4].[T_PRODUCTOS]
(
	[ID_PRODUCTO] INT NOT NULL,
	[NOMBRE] VARCHAR(200) NOT NULL,
	[DESCRIPCION] VARCHAR(200) NOT NULL,
	[PRECIO] DECIMAL NOT NULL,
	[ESTADO] BIT NOT NULL DEFAULT(1),
	[CANTIDAD] INT NOT NULL,
	[ID_TIPO_PRODUCTO] INT NOT NULL


	CONSTRAINT [PK_T_PRODUCTOS] PRIMARY KEY CLUSTERED
	(
		[ID_PRODUCTO] ASC
	)
)
GO

CREATE TABLE [SCH_FARMACIA_PROGRA4].[T_CLIENTES]
(
[ID_CLIENTE] INT NOT NULL,
[IDENTIFICACION] VARCHAR(50) NOT NULL,
[NOMBRE_CLIENTE] VARCHAR(50) NOT NULL,
[APELLIDO] VARCHAR(50) NOT NULL,
[CORREO] VARCHAR(50) NOT NULL

	CONSTRAINT [PK_T_CLIENTES] PRIMARY KEY CLUSTERED 
	(
	[ID_CLIENTE] ASC
	)
)
GO

CREATE TABLE [SCH_FARMACIA_PROGRA4].[T_FACTURAS]
(
[ID_FACTURA] INT NOT NULL,
[FECHA_COMPRA] DATETIME NOT NULL,
[CANTIDAD] INT NOT NULL,
[MONTO_TOTAL] DECIMAL (10,2) NOT NULL,
[ESTADOACTIVO] BIT NOT NULL DEFAULT (1),
[ID_CLIENTE] INT NOT NULL,
[ID_USUARIO] INT NOT NULL,
[ID_PRODUCTO] INT NOT NULL

CONSTRAINT [PK_T_FACTURAS] PRIMARY KEY CLUSTERED 
	(
	[ID_FACTURA] ASC
	)
)
GO



--LLAVES FORANEAS--  
----------------------------------------------------------------------------FORANEA FACTURAS----------------------------------------------------------------------------
ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_FACTURAS]
ADD CONSTRAINT [FK_FACTURA_ID_CLIENTE] FOREIGN KEY (ID_CLIENTE)
REFERENCES [SCH_FARMACIA_PROGRA4].[T_CLIENTES] 
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_FACTURAS]
CHECK CONSTRAINT [FK_FACTURA_ID_CLIENTE]
GO

ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_FACTURAS]
ADD CONSTRAINT [FK_FACTURA_ID_USUARIO] FOREIGN KEY (ID_USUARIO)
REFERENCES [SCH_FARMACIA_PROGRA4].[T_USUARIOS] 
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_FACTURAS]
CHECK CONSTRAINT [FK_FACTURA_ID_USUARIO]
GO

ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_FACTURAS]
ADD CONSTRAINT [FK_FACTURA_ID_PRODUCTO] FOREIGN KEY (ID_PRODUCTO)
REFERENCES [SCH_FARMACIA_PROGRA4].[T_PRODUCTOS] 
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_FACTURAS]
CHECK CONSTRAINT [FK_FACTURA_ID_PRODUCTO]
GO
----------------------------------------------------------------------------FORANEA ROLES----------------------------------------------------------------------------
ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_USUARIOS]
ADD CONSTRAINT [FK_T_USUARIO_T_ROLE_USUARIO] FOREIGN KEY (ID_ROLE)
REFERENCES [SCH_FARMACIA_PROGRA4].[T_ROLES]
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_USUARIOS]
CHECK CONSTRAINT [FK_T_USUARIO_T_ROLE_USUARIO]
GO

----------------------------------------------------------------------------FORANEA PRODUCTO----------------------------------------------------------------------------
ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_PRODUCTOS]
ADD CONSTRAINT [FK_T_PRODUCTO_TIPO_PRODUCTO] FOREIGN KEY (ID_TIPO_PRODUCTO)
REFERENCES [SCH_FARMACIA_PROGRA4].[T_TIPO_DE_PRODUCTOS]
GO
ALTER TABLE [SCH_FARMACIA_PROGRA4].[T_PRODUCTOS]
CHECK CONSTRAINT [FK_T_PRODUCTO_TIPO_PRODUCTO]
GO




-- Insertar roles
INSERT INTO [SCH_FARMACIA_PROGRA4].[T_ROLES] (ID_ROLE, NOMBRE) VALUES
(1, 'administrador'),
(2, 'vendedor'),
(3, 'contador');

-- Insertar usuarios
INSERT INTO [SCH_FARMACIA_PROGRA4].[T_USUARIOS] (ID_USUARIO, IDENTIFICACION, NOMBRE, APELLIDO, CORREO, CLAVE, ID_ROLE) VALUES
(1, '1111', 'pablo', 'camacho', 'fake@email.com', 'admin', 1),
(2, '2222', 'mike', 'VendedorApellido', 'vendedor@example.com', 'claveVendedor', 2),
(3, '333', 'jean', 'ContadorApellido', 'contador@example.com', 'claveContador', 3);

-- Insertar tipos de productos
INSERT INTO [SCH_FARMACIA_PROGRA4].[T_TIPO_DE_PRODUCTOS] (ID_TIPO_PRODUCTO, NOMBRE_TIPO_PRODUCTO, DESCRIPCION) VALUES
(1, 'medicina', 'Medicamentos recetados'),
(2, 'cuidado personal', 'Productos de cuidado personal'),
(3, 'salud y bienestar', 'Productos para el bienestar general');

-- Insertar productos
INSERT INTO [SCH_FARMACIA_PROGRA4].[T_PRODUCTOS] (ID_PRODUCTO, NOMBRE, DESCRIPCION, PRECIO, ESTADO, CANTIDAD, ID_TIPO_PRODUCTO) VALUES
(1, 'paracetamol', 'Analg�sico y antipir�tico', 7000, 1, 100, 1),
(2, 'champ� Anticaspa', 'Elimina la caspa y alivia la picaz�n', 18000, 1, 50, 2),
(3, 'vitamina C', 'Suplemento de vitamina C', 585, 1, 75, 3);

-- Insertar clientes
INSERT INTO [SCH_FARMACIA_PROGRA4].[T_CLIENTES] (ID_CLIENTE, IDENTIFICACION, NOMBRE_CLIENTE, APELLIDO, CORREO) VALUES
(1, 'C001', 'Cliente1', 'ApellidoCliente1', 'cliente1@example.com'),
(2, 'C002', 'Cliente2', 'ApellidoCliente2', 'cliente2@example.com');

-- Insertar facturas
INSERT INTO [SCH_FARMACIA_PROGRA4].[T_FACTURAS] (ID_FACTURA, FECHA_COMPRA,CANTIDAD, MONTO_TOTAL, ESTADOACTIVO, ID_CLIENTE, ID_USUARIO, ID_PRODUCTO) VALUES
(3, '2023-11-01',2, 5000, 1, 1, 2, 1),
(4, '2023-11-02',5,6000, 1, 2, 1, 3);



-- consultas:
-- roles
SELECT * FROM [SCH_FARMACIA_PROGRA4].[T_ROLES];

-- usuarios con roles
SELECT U.*, R.NOMBRE AS NOMBRE_ROL
FROM [SCH_FARMACIA_PROGRA4].[T_USUARIOS] U
JOIN [SCH_FARMACIA_PROGRA4].[T_ROLES] R ON U.ID_ROLE = R.ID_ROLE;


-- tipos de productos
SELECT * FROM [SCH_FARMACIA_PROGRA4].[T_TIPO_DE_PRODUCTOS];


SELECT P.*, TP.NOMBRE_TIPO_PRODUCTO
FROM [SCH_FARMACIA_PROGRA4].[T_PRODUCTOS] P
JOIN [SCH_FARMACIA_PROGRA4].[T_TIPO_DE_PRODUCTOS] TP ON P.ID_TIPO_PRODUCTO = TP.ID_TIPO_PRODUCTO;


-- clientes

SELECT * FROM [SCH_FARMACIA_PROGRA4].[T_CLIENTES];


-- clientes productos y usuarios

SELECT F.*, C.NOMBRE_CLIENTE, U.NOMBRE AS NOMBRE_USUARIO, P.NOMBRE AS NOMBRE_PRODUCTO
FROM [SCH_FARMACIA_PROGRA4].[T_FACTURAS] F
JOIN [SCH_FARMACIA_PROGRA4].[T_CLIENTES] C ON F.ID_CLIENTE = C.ID_CLIENTE
JOIN [SCH_FARMACIA_PROGRA4].[T_USUARIOS] U ON F.ID_USUARIO = U.ID_USUARIO
JOIN [SCH_FARMACIA_PROGRA4].[T_PRODUCTOS] P ON F.ID_PRODUCTO = P.ID_PRODUCTO;
