//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIV_PF_ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FACTURAS
    {
        public int ID_FACTURA { get; set; }
        public System.DateTime FECHA_COMPRA { get; set; }
        public decimal MONTO_TOTAL { get; set; }
        public bool ESTADOACTIVO { get; set; }
    
        public virtual T_CLIENTES T_CLIENTES { get; set; }
        public virtual T_PRODUCTOS T_PRODUCTOS { get; set; }
        public virtual T_USUARIOS T_USUARIOS { get; set; }
    }
}
